### ISSUE TITLE
makeCross2 and ID problem

### ISSUE THREAD

**Issue by AudreyAAMartin** [gaynorr/AlphaSimR#142] opened 2023-07-04 13:59 UTC
**Describe the bug**
The function makeCross2 (from crossing.R) creates new individuals based on a pop and a crossing plan. If the crossing plan (and the pop) has numerical ID that are different than 1:nInd, you get the error 'Invalid crossPlan'. The error is coming from the step checking that the crossPlan and pop information match (see below). 

```
if((max(crossPlan[,1])>nInd(females)) | 
     (max(crossPlan[,2])>nInd(males)) |
     (min(crossPlan)<1L)){
    stop("Invalid crossPlan")
  }
```

**Steps To Reproduce**
```
library(AlphaSimR)
#Create founder haplotypes
founderPop = quickHaplo(nInd=4, nChr=1, segSites=10)
#Set simulation parameters
SP = SimParam$new(founderPop)
#Create population
pop = newPop(founderPop, simParam=SP)
#numerical ID that are bigger than the pop size (or simply != 1:nInd)
pop@id = c("10", "11", "12", "13", "14")
#Cross individual 13 with individual 14
crossPlan = c(13, 14)
pop2 = makeCross(pop, crossPlan, simParam=SP)
```

**Expected behavior**
The function is creating new individuals based on a crossing plan. It should run fine no matter the 'value' of numerical ID.

**Comment by gregorgorjanc** [comment] 2023-07-04 15:09
@AudreyAAMartin I think the issue is with the character ID's recently introduced. Would replacing

```
if((max(crossPlan[,1])>nInd(females)) | 
     (max(crossPlan[,2])>nInd(males)) |
     (min(crossPlan)<1L)){
    stop("Invalid crossPlan")
  }
```

with 

```
if(any(!crossPlan[, 1] %in% females@id)) | 
     (any(!crossPlan[, 2] %in% males@id)) {
    stop("Invalid crossPlan")
  }
```

solve the problem? BUT, we need to ensure we are picking the right parents down the line in the code too!

**Comment by AudreyAAMartin** [comment] 2023-07-04 15:46
@gregorgorjanc It is definitely linked to the ID problem! 
The replacement did solve that part of the problem but the function still does not function properly. I tracked it back to makeCross2() -> newPop() -> .newPop() -> setMethod for RawPop Extract RawPop by index where: 

```
setMethod("[",
          signature(x = "RawPop"),
          function(x, i){
            if(any(abs(i)>x@nInd)){
              stop("Trying to select invalid individuals")
            }
            for(chr in 1:x@nChr){
              x@geno[[chr]] = x@geno[[chr]][,,i,drop=FALSE]
            }
            x@nInd = dim(x@geno[[1]])[3]
            return(x)
          }
)
```

(x is a pop object and i an individual) 
It is the if statement who's problematic but changing it will have consequences on more than just makeCross2()...

**Comment by gaynorr** [comment] 2023-07-04 16:32
@gregorgorjanc your code above is failing because you are selecting from `pop` and not `pop2` as intended.

@AudreyAAMartin, as Gregor shows there is currently a dual behavior for either character variables or numeric variables when you call population subsetting or crossing. When you supply numeric values, AlphaSimR looks for individuals according to their position in the populations. If you provide character variables, AlphaSimR will look for individuals according to their ID. This second functionality was added later. 

A couple of changes need to be made to the original code. First, there are 4 individuals in the initial population, but 5 new IDs are generated. I added an additional individual to the founder population to correct this. Then you just need to pass the IDs as characters and they need to be in a matrix with two columns. Here is my code below.

```
library(AlphaSimR)
#Create founder haplotypes
founderPop = quickHaplo(nInd=5, nChr=1, segSites=10)
#Set simulation parameters
SP = SimParam$new(founderPop)
#Create population
pop = newPop(founderPop, simParam=SP)
#numerical ID that are bigger than the pop size (or simply != 1:nInd)
pop@id = c("10", "11", "12", "13", "14")
#Cross individual 13 with individual 14
crossPlan = cbind("13", "14")
pop2 = makeCross(pop, crossPlan, simParam=SP)
```

**Comment by gregorgorjanc** [comment] 2023-07-04 16:37
For completness - current character code fails

```
> pop2 = randCross(pop, nCrosses = 5)
> pop2@id
[1] "10" "11" "12" "13" "14"
> pop2[c(5, 1)]@id
[1] "14" "10"
> pop2[c("9", "5")]@id
Error in .local(x, i, ...) : Trying to select invalid individuals
```

**Comment by gaynorr** [comment] 2023-07-04 16:42
Closing the issue.

**Closed by gaynorr** 2023-07-04 16:42 UTC
